# 修改启动端口为9090
server:
  port: 9090

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/schoolbbs?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  mail:
    protocol: smtps
    host: smtp.qq.com
    username: 1651347056@qq.com
    password: udhqrdjpsfumcdgg
    port: 465
    default-encoding: UTF-8
      # 设置开启ssl
    properties:
      mail:
         stmp:
          ssl:
            enable: true

# 扫描mapper目录下所有mybatis的xml文件
mybatis:
  mapper-locations: classpath:mapper/*.xml

# mybatis输出日志
# mybatis.configuration.log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # mybatis-plus的自动驼峰命名规则
  # configuration:
  #   map-underscore-to-camel-case: false

# 上传文件的路径
files:
  upload:
    path: F:/upload/

