/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AdminInfo: typeof import('./src/components/admin/adminInfo.vue')['default']
    Bankuai: typeof import('./src/components/admin/bankuai.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCalendar: typeof import('element-plus/es')['ElCalendar']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElText: typeof import('element-plus/es')['ElText']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    Forum: typeof import('./src/components/user/forum.vue')['default']
    Ggg: typeof import('./src/components/user/ggg.vue')['default']
    Identify: typeof import('./src/components/other/identify.vue')['default']
    Links: typeof import('./src/components/other/links.vue')['default']
    Map: typeof import('./src/components/user/map.vue')['default']
    MyBtn: typeof import('./src/components/other/my-btn.vue')['default']
    MyFavorites: typeof import('./src/components/user/myFavorites.vue')['default']
    MyLike: typeof import('./src/components/user/myLike.vue')['default']
    MyReply: typeof import('./src/components/user/myReply.vue')['default']
    Overview: typeof import('./src/components/admin/overview.vue')['default']
    Post: typeof import('./src/components/admin/post.vue')['default']
    PostContent: typeof import('./src/components/user/postContent.vue')['default']
    PostList: typeof import('./src/components/user/postList.vue')['default']
    ReplyPost: typeof import('./src/components/admin/replyPost.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./src/components/user/search.vue')['default']
    UserInfo: typeof import('./src/components/admin/userInfo.vue')['default']
    UserPwd: typeof import('./src/components/admin/user-pwd.vue')['default']
    UserRole: typeof import('./src/components/admin/userRole.vue')['default']
  }
  export interface ComponentCustomProperties {
    vInfiniteScroll: typeof import('element-plus/es')['ElInfiniteScroll']
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
